version: '3.8'

services:
  backend:
    container_name: ecom_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - ecom_network

networks:
  ecom_network:
    external: true
